version: '3'

services:
  influxdb:
    image: docker.io/bitnami/influxdb:2
    container_name: influxdb
    ports:
      - 28086:8086
      - 28088:8088
    networks:
      - grafana-network
    env_file: .env-influx
    volumes:
      #- ./influxdb.conf:/opt/bitnami/influxdb/etc/influxdb.conf:ro
      - influxdb_data:/bitnami/influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./custom.ini:/etc/grafana/custom.ini:ro
    networks:
      - grafana-network
    ports:
      - 23000:3000
    env_file: .env-grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
      - GF_LOG_LEVEL=debug
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource

volumes:
  influxdb_data:
    driver: local
    name: influxdb
  grafana_data:
    driver: local
    name: grafana

networks:
  grafana-network:
    driver: bridge
