version: '2'

services:
  influxdb:
    image: docker.io/bitnami/influxdb:2
    container_name: influxdb
    ports:
      - 8086:8086
      - 8088:8088
    networks:
      - my-network
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      #- ./influxdb.conf:/opt/bitnami/influxdb/etc/influxdb.conf:ro
      - influxdb_data:/bitnami/influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 1m30s
      timeout: 2s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my-network
    ports:
      - 3000:3000
    user: '501'
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource, https://github.com/VolkovLabs/custom-plugin.zip;custom-plugin

volumes:
  influxdb_data:
    driver: local
    name: influxdb
  grafana_data:
    driver: local
    name: grafana

networks:
  my-network:
    driver: bridge
